negative <- c("aggression", "aggressive", "agitated", "anger", "angry",
  "anxiety", "anxiety_disorder", "anxious", "appetite", "ashamed",
  "assaultive", "attack", "avoidance", "avoidant", "blue", "calm",
  "chest", "chest_pain", "chill", "constricted", "depressed", "depressed_mood",
  "depressive", "depressive_disorder", "diaphoretic", "diarrhea",
  "difficulty", "down", "dysphoric", "dysthymic", "emotional",
  "energy", "fatigue", "fearful", "feelings", "fever", "frighten",
  "gain", "guilt", "guilty", "head", "helpless", "hopeful", "hopelessness",
  "hypervigilant", "irritable", "lesion", "living", "major", "meaningless",
  "nausea", "nervous", "optimistic", "outburst", "palpitation",
  "panic", "panic_attack", "panic_disorder", "pessimistic", "phobia",
  "phobic", "posttraumatic", "posttraumatic_stress", "refuse",
  "relaxed", "respond", "sad", "scare", "sensory", "sensory_deficit",
  "situation", "startle", "stress", "stress_disorder", "stressor",
  "suicidal", "sweat", "tachycardic", "tearful", "tense", "threaten",
  "trauma", "tremulous", "violence", "violent", "weight_gain",
  "worried", "worth", "worthless")
positive <- c("abuse", "alcohol", "alcohol_abuse",
  "alcohol_dependance", "alcohol_withdrawal", "appetite", "back",
  "barbiturate", "blackout", "bowel", "compulsive", "count", "couple",
  "craving", "cut", "dependance", "disorder_nos", "drink", "drug",
  "effect", "etoh", "financial", "gamble", "heavy", "heroin", "high",
  "high_school", "hoard", "indication", "induce", "induce_mood",
  "ingestion", "intake", "interest", "intoxicate", "intoxication",
  "liver", "lose", "money", "monitoring", "motivate", "motor",
  "movement", "ordering", "partial", "planning", "psychotic_disorder",
  "related", "remission", "repetitive", "report_that", "resource",
  "routine", "sexual_abuse", "stereotypy", "stop", "strategy",
  "therapy", "with_alcohol", "withdrawal", "withdrawal_symptom")
cognitive <- c("ability", "answer", "aphasic", "attention", "attentive",
  "auditory", "auditory_hallucination", "behavior", "cognitive",
  "compliance", "content", "conversation", "conviction", "current_episode",
  "decrease_need", "delusion", "disinhibit", "disorganisation",
  "disorganise", "disorganise_behavior", "distracted", "distractible",
  "employ", "engage", "executive", "exercise", "factor_include",
  "fast", "flight", "forget", "forgetful", "grandiosity", "hallucinate",
  "hallucination", "idea", "illusion", "impairment", "impulse",
  "impulsive", "impulsive_behavior", "inappropriate", "incoherent",
  "information", "injurious_behavior", "insertion", "intact", "irritable",
  "memory", "mildly", "name", "ongoing", "perception", "planning",
  "possibly", "problem", "psychotic", "psychotic_disorder", "psychotic_feature",
  "question", "race", "recall", "regularly", "related", "schizophrenia",
  "sensation", "sexual_abuse", "sweat", "talk", "term", "testing",
  "thought", "thought_insertion", "type", "ultimately", "understand",
  "understanding", "visual", "visual_hallucination", "voice", "vomiting",
  "with_psychotic", "word")
social <- c("aggressive", "auditory", "auditory_hallucination",
  "behavior", "belief", "compliance", "concern_that", "content",
  "control", "current_episode", "delusion", "delusional", "disorder_nos",
  "disorganise", "elicit", "empathic", "engaged", "expressive",
  "fast", "flat", "grandiose", "hallucinate", "hallucination",
  "impulse", "impulse_control", "inappropriate", "interview", "isolated",
  "language", "lonely", "misinterpret", "misunderstand", "paranoid",
  "paranoid_ideation", "partial", "prominent", "psychotic", "psychotic_disorder",
  "psychotic_feature", "regular", "related", "theme", "think",
  "thought_broadcasting", "threaten", "type", "vague", "visual",
  "voice", "wall", "with_psychotic", "withdrawn", "worthless")
arousal_regulatory <- c("abnormality", "agitated", "agitation", "alertness", "alfa",
  "amount", "apnea", "appetite", "architecture", "attention",
  "bipap", "blink", "cardiovascular", "chest_pain", "chill",
  "cigaret", "circadian", "compare", "concentration", "continuity",
  "cortisol", "cpap", "deficit", "deprivation", "difficulty",
  "dizziness", "dream", "duration", "eeg", "emotional", "energy",
  "executive_function", "express", "fatigue", "faze", "feelings",
  "ferritin", "fragmentation", "have_been", "headache", "hormone",
  "hour", "hypersomnia", "identify", "information", "insomnia",
  "irritability", "language", "melatonin", "memory", "minutes",
  "motivate", "motor", "motor_activity", "neck", "night", "nightmare",
  "notice", "offer", "oral", "osa", "posttraumatic", "posttraumatic_stress",
  "psychomotor", "psychomotor_agitation", "quantity", "range",
  "reactivity", "rem_sleep", "respiratory", "restless", "restoration",
  "rhythm", "sensation", "sensitivity", "sensory", "sensory_deficit",
  "sexual_abuse", "sleep_latency", "sleep_study", "sleepiness",
  "someone_else", "spindle", "stability", "stable", "startle",
  "stress", "stress_disorder", "symptom_include", "these_problem",
  "theta", "timing", "tingle", "tired", "trauma", "traumatic",
  "user", "variability", "vigilance", "voluntary", "wakefulness",
  "waking", "weight_gain", "with_general", "worsen")